ifndef CONTIKI_TARGET_MAIN
CONTIKI_TARGET_MAIN = contiki-shimmer-main.c
endif

CONTIKI_TARGET_DIRS = . dev
CONTIKI_TARGET_SOURCEFILES += $(CONTIKI_TARGET_MAIN) \
adc.c \
bluetooth.c \
busmaster.c \
ds2411.c \
gyro.c \
hmc5843.c \
uart0.c \
uart1.c

MCU=msp430f1611
include $(CONTIKI)/cpu/msp430/Makefile.msp430
